name = "brainboom-worker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "brainboom-db"
database_id = "dac3b9d5-ddbb-400f-a360-dffa555343fc"

[[r2_buckets]]
binding = "R2"
bucket_name = "brainboom-uploads"

[[kv_namespaces]]
binding = "KV"
id = "4ace97acae5448dd91e8f654840b0ac0"

[durable_objects]
bindings = [
  { name = "CHAT_ROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[vars]
ENVIRONMENT = "production"
