import { Question } from "@/types";

export const QUESTIONS: Question[] = [
  {
    id: 1,
    emoji: "🦁",
    text: "Siapa raja hutan?",
    answers: ["singa", "lion", "raja hutan", "singa raja hutan"],
    hints: ["Hewan berambut lebat", "Suka mengaum"],
  },
  {
    id: 2,
    emoji: "🍎",
    text: "Buah apa yang jatuh di kepala Newton?",
    answers: ["apel", "apple", "buah apel"],
    hints: ["Warnanya merah", "Ada bijinya"],
  },
  {
    id: 3,
    emoji: "🇮🇩",
    text: "Ibukota Indonesia adalah?",
    answers: ["jakarta", "dki jakarta", "jakarta pusat"],
    hints: ["Di pulau Jawa", "Pernah jadi Batavia"],
  },
  {
    id: 4,
    emoji: "🌙",
    text: "Bulan memiliki bentuk seperti apa saat purnama?",
    answers: ["bulat", "lingkaran", "bundar", "penuh", "bulat penuh"],
    hints: ["Tidak ada sudut", "Mirip matahari"],
  },
  {
    id: 5,
    emoji: "🐘",
    text: "Hewan apa yang memiliki belalai panjang?",
    answers: ["gajah", "elephant", "hewan gajah"],
    hints: ["Hidupnya di darat", "Suka mandi lumpur"],
  },
  {
    id: 6,
    emoji: "🌊",
    text: "Samudra terbesar di dunia adalah?",
    answers: ["pasifik", "samudra pasifik", "pacific", "laut pasifik"],
    hints: ["Di antara Asia dan Amerika", "Nama artinya 'damai'"],
  },
  {
    id: 7,
    emoji: "🎨",
    text: "Siapa pelukis Mona Lisa?",
    answers: ["leonardo da vinci", "da vinci", "leonardo", "vinci"],
    hints: ["Dari Italia", "Juga ilmuwan"],
  },
  {
    id: 8,
    emoji: "⚽",
    text: "Berapa jumlah pemain sepak bola dalam satu tim?",
    answers: ["11", "sebelas", "11 orang", "sebelas orang"],
    hints: ["Lebih dari 10", "Kurang dari 12"],
  },
  {
    id: 9,
    emoji: "🍫",
    text: "Makanan manis yang terbuat dari kakao adalah?",
    answers: ["coklat", "cokelat", "chocolate", "coklat batang"],
    hints: ["Bisa meleleh", "Warnanya cokelat"],
  },
  {
    id: 10,
    emoji: "🦅",
    text: "Burung apa yang menjadi lambang negara Indonesia?",
    answers: ["garuda", "garuda pancasila", "elang", "garuda indonesia"],
    hints: ["Makhluk mitologi", "Memiliki banyak kepala dalam cerita"],
  },
  {
    id: 11,
    emoji: "🌋",
    text: "Gunung berapi tertinggi di Indonesia adalah?",
    answers: ["kerinci", "gunung kerinci", "mt kerinci", "kerinci sumatera"],
    hints: ["Di Sumatera", "Tingginya 3.805 meter"],
  },
  {
    id: 12,
    emoji: "🎵",
    text: "Alat musik yang dimainkan dengan tiup adalah?",
    answers: ["seruling", "flute", "suling", "terompet", "trompet", "saxophone", "saksofon"],
    hints: ["Butuh napas", "Bunyi dari lubang kecil"],
  },
  {
    id: 13,
    emoji: "🐳",
    text: "Mamalia laut terbesar adalah?",
    answers: ["paus biru", "blue whale", "paus", "whale"],
    hints: ["Warnanya biru", "Jantungnya sebesar mobil"],
  },
  {
    id: 14,
    emoji: "📚",
    text: "Siapa penulis Harry Potter?",
    answers: ["jk rowling", "j.k. rowling", "joanne rowling", "rowling"],
    hints: ["Dari Inggris", "Namanya berawalan J"],
  },
  {
    id: 15,
    emoji: "🌵",
    text: "Tumbuhan apa yang tumbuh di gurun?",
    answers: ["kaktus", "cactus", "kaktus gurun"],
    hints: ["Ber duri", "Simpan air dalam batang"],
  },
  {
    id: 16,
    emoji: "🚗",
    text: "Siapa penemu mobil bermesin bensin pertama?",
    answers: ["karl benz", "benz", "karl friedrich benz"],
    hints: ["Dari Jerman", "Namanya jadi merek mobil"],
  },
  {
    id: 17,
    emoji: "🍕",
    text: "Makanan khas Italia yang berbentuk bulat adalah?",
    answers: ["pizza", "piza", "pizza italia"],
    hints: ["Ada topping di atasnya", "Biasanya diiris segitiga"],
  },
  {
    id: 18,
    emoji: "🦘",
    text: "Hewan apa yang melompat untuk bergerak?",
    answers: ["kanguru", "kangaroo", "kangguru"],
    hints: ["Dari Australia", "Memiliki kantung"],
  },
  {
    id: 19,
    emoji: "🌈",
    text: "Berapa warna dalam pelangi?",
    answers: ["7", "tujuh", "7 warna", "tujuh warna"],
    hints: ["Ingat singkatan MEJIKUHIBINIU", "Lebih dari 5 kurang dari 10"],
  },
  {
    id: 20,
    emoji: "🦈",
    text: "Ikan predator yang memiliki banyak gigi tajam adalah?",
    answers: ["hiu", "shark", "ikan hiu", "white shark"],
    hints: ["Dikenal ganas", "Film Jaws tentang dia"],
  },
  {
    id: 21,
    emoji: "🏔️",
    text: "Gunung tertinggi di dunia adalah?",
    answers: ["everest", "gunung everest", "mt everest", "sagarmatha"],
    hints: ["Di perbatasan Nepal dan Tibet", "Tingginya 8.848 meter"],
  },
  {
    id: 22,
    emoji: "🎸",
    text: "Siapa gitaris legendaris band The Beatles?",
    answers: ["john lennon", "lennon", "paul mccartney", "mccartney", "george harrison", "harrison"],
    hints: ["Dari Liverpool", "Satu dari empat personel"],
  },
  {
    id: 23,
    emoji: "🐧",
    text: "Burung apa yang tidak bisa terbang?",
    answers: ["pinguin", "penguin", "burung pinguin"],
    hints: ["Hidup di kutub", "Bisa berenang"],
  },
  {
    id: 24,
    emoji: "🌻",
    text: "Bunga apa yang selalu menghadap ke matahari?",
    answers: ["bunga matahari", "sunflower", "matahari"],
    hints: ["Warnanya kuning", "Bijinya bisa dimakan"],
  },
  {
    id: 25,
    emoji: "🚀",
    text: "Negara apa yang pertama kali mengirim manusia ke bulan?",
    answers: ["amerika", "usa", "amerika serikat", "united states", "as"],
    hints: ["Benderanya berbintang", "Neil Armstrong dari sana"],
  },
  {
    id: 26,
    emoji: "🐝",
    text: "Serangga apa yang menghasilkan madu?",
    answers: ["lebah", "bee", "lebah madu", "honey bee"],
    hints: ["Hidup berkoloni", "Suka bunga"],
  },
  {
    id: 27,
    emoji: "🎭",
    text: "Kota apa yang terkenal dengan kanal-kanalnya?",
    answers: ["venesia", "venice", "venezia", "venice italia"],
    hints: ["Di Italia", "Transportasi utamanya gondola"],
  },
  {
    id: 28,
    emoji: "🦖",
    text: "Dinosaurus terbesar yang pernah hidup adalah?",
    answers: ["argentinosaurus", "titanosaurus", "brachiosaurus", "apatosaurus"],
    hints: ["Herbivora", "Lehernya sangat panjang"],
  },
  {
    id: 29,
    emoji: "🌏",
    text: "Planet ketiga dari matahari adalah?",
    answers: ["bumi", "earth", "planet bumi", "dunia"],
    hints: ["Kita tinggal di sini", "Ada air di permukaannya"],
  },
  {
    id: 30,
    emoji: "🏆",
    text: "Olahraga apa yang menggunakan raket dan kok?",
    answers: ["bulutangkis", "badminton", "bulu tangkis"],
    hints: ["Populer di Indonesia", "Butuh net di tengah"],
  },
];

export const ROASTS = [
  "Aduh, kok bisa salah sih? 🤦",
  "Mbah BrainBoom kecewa nih... 😔",
  "Coba lagi, jangan nyerah! 💪",
  "Hmm, masih kurang tepat nih 🤔",
  "Otakmu perlu diasah dulu kayaknya 🔪",
  "Salah lagi? Mbah mulai pesimis nih 😅",
  "Jawabanmu bikin Mbah pusing 🤯",
  "Coba pikir lebih keras! 🧠",
  "Hmm, bukan itu jawabannya 🤷",
  "Mbah yakin kamu bisa lebih baik! 🌟",
  "Aduh, jauh dari benar nih 😂",
  "Coba minum kopi dulu biar fokus ☕",
  "Jawabanmu bikin Mbah tertawa 🤣",
  "Hmm, sepertinya perlu hint nih? 💡",
  "Mbah percaya kamu pasti bisa! 🙌",
  "Salah lagi? Mbah mulai khawatir 😰",
  "Coba pikir dari sudut lain! 🔄",
  "Jawabanmu unik, tapi salah 😅",
  "Mbah yakin otakmu sedang loading... ⏳",
  "Hmm, bukan itu yang Mbah cari 🔍",
];

export const PRAISES = [
  "Wah, benar! Mbah bangga! 🎉",
  "Hebat! Kamu jenius! 🌟",
  "Tepat sekali! Lanjutkan! 👏",
  "Mbah terkesan! Luar biasa! 🤩",
  "Benar! Kamu makin pintar! 📈",
  "Tepat! Mbah senang melihatmu! 😊",
  "Wah, jawabanmu sempurna! ✨",
  "Hebat! Mbah jadi semangat! 🔥",
  "Benar! Kamu memang hebat! 💪",
  "Tepat! Mbah jadi bangga! 🥰",
  "Wah, kamu makin jago! 🚀",
  "Benar! Teruskan prestasimu! 🏆",
  "Mbah terpukau! Jawabanmu tepat! 🤯",
  "Hebat! Kamu calon juara! 🥇",
  "Tepat! Mbah senang sekali! 🎊",
  "Benar! Kamu memang cerdas! 🧠",
  "Wah, Mbah jadi terharu! 🥹",
  "Tepat! Kamu memang terbaik! 👑",
  "Benar! Mbah jadi semangat! 💥",
  "Hebat! Kamu bikin Mbah bangga! 🌈",
];
